### ISSUE TITLE
[Suggestion] Use the official iMDB datasets

### ISSUE THREAD

**Issue by KurtzPT** [Joost1991/plex-imdb-updater#1]
Using the official datasets of IMDB (https://datasets.imdbws.com/) is in my eyes the fastest and best way to update ratings:

- Updated every day (Not sure of this, but certainly updated way more frequently than websites like OMDB)
- You only need to download the title.ratings.tsv.gz each time you run the app. Every single rating in IMDB database is inside that file so every single request for a rating would be locally to that file instead of an API call remotely.

The only "cons" is that you need to implement a CSV type of parser to read the file after extracting it.

**Comment by Joost1991** [comment]
Thanks for the suggestion! Didn't know about this source.

Will have a look if I can implement this, since it's also much faster probably.
